# Generated by Django 5.0.6 on 2026-05-22 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('est_lue', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=200, null=True)),
                ('avatar_url', models.CharField(blank=True, max_length=500, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('context_image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.utilisateur')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
