# Generated by Django 5.0.6 on 2026-04-15 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'administrateur',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('est_verifie', models.BooleanField(default=False)),
                ('statut_compte', models.CharField(default='actif', max_length=50)),
            ],
            options={
                'db_table': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=20)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
            ],
            options={
                'db_table': 'disponibilite',
            },
        ),
        migrations.CreateModel(
            name='Recruteur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.utilisateur')),
                ('nom_structure', models.CharField(max_length=200)),
                ('type_structure', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('note_globale', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'recruteur',
            },
            bases=('users.utilisateur',),
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.utilisateur')),
                ('competences', models.JSONField(default=list)),
                ('experience', models.TextField(blank=True, null=True)),
                ('note_globale', models.FloatField(default=0.0)),
                ('disponibilites', models.ManyToManyField(blank=True, related_name='candidats', to='users.disponibilite')),
                ('portfolio', models.ManyToManyField(blank=True, related_name='candidats', to='uploads.media')),
            ],
            options={
                'db_table': 'candidat',
            },
            bases=('users.utilisateur',),
        ),
    ]
