# Generated by Django 5.0.6 on 2026-05-22 04:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'administrateur',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('est_verifie', models.BooleanField(default=False)),
                ('statut_compte', models.CharField(default='actif', max_length=50)),
                ('push_notif_enabled', models.BooleanField(default=True)),
                ('avatar_url', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('push_token', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='CandidateSkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'candidate_skill_group',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=20)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
            ],
            options={
                'db_table': 'disponibilite',
            },
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_otp',
            },
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.utilisateur')),
                ('competences', models.JSONField(default=list)),
                ('experience', models.TextField(blank=True, null=True)),
                ('note_globale', models.FloatField(default=0.0)),
                ('titre_poste', models.CharField(blank=True, max_length=100)),
                ('domain', models.CharField(blank=True, max_length=100)),
                ('disponibilites', models.ManyToManyField(blank=True, related_name='candidats', to='users.disponibilite')),
            ],
            options={
                'db_table': 'candidat',
            },
            bases=('users.utilisateur',),
        ),
        migrations.CreateModel(
            name='Recruteur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.utilisateur')),
                ('nom_structure', models.CharField(max_length=200)),
                ('type_structure', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('note_globale', models.FloatField(default=0.0)),
                ('titre_poste', models.CharField(blank=True, max_length=200, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'recruteur',
            },
            bases=('users.utilisateur',),
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('expert', 'Expert')], max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='users.candidateskillgroup')),
            ],
            options={
                'db_table': 'candidate_skill',
            },
        ),
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_searches', to='users.utilisateur')),
            ],
            options={
                'db_table': 'recent_search',
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('dark_mode', models.BooleanField(default=False)),
                ('language_code', models.CharField(default='fr', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='users.utilisateur')),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
        migrations.CreateModel(
            name='CvFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='users.candidat')),
            ],
            options={
                'db_table': 'cv_formation',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='CvExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
                ('end_date', models.CharField(blank=True, max_length=50, null=True)),
                ('is_app_mission', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='users.candidat')),
            ],
            options={
                'db_table': 'cv_experience',
            },
        ),
        migrations.CreateModel(
            name='CandidateTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='users.candidat')),
            ],
            options={
                'db_table': 'candidate_tool',
            },
        ),
        migrations.AddField(
            model_name='candidateskillgroup',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_groups', to='users.candidat'),
        ),
        migrations.CreateModel(
            name='CandidateLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('proficiency', models.CharField(max_length=50)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='users.candidat')),
            ],
            options={
                'db_table': 'candidate_language',
            },
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_blocage', models.DateTimeField(auto_now_add=True)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloque_par', to='users.utilisateur')),
                ('bloqueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs_bloques', to='users.utilisateur')),
            ],
            options={
                'db_table': 'blocked_user',
                'unique_together': {('bloqueur', 'bloque')},
            },
        ),
        migrations.CreateModel(
            name='RestrictedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_restriction', models.DateTimeField(default=django.utils.timezone.now)),
                ('restreint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions_recues', to='users.utilisateur')),
                ('restricteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions_donnees', to='users.utilisateur')),
            ],
            options={
                'db_table': 'restricted_user',
                'unique_together': {('restricteur', 'restreint')},
            },
        ),
    ]
