# Generated by Django 5.0.6 on 2026-04-26 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='portfolio',
        ),
    ]
