# Generated by Django 5.0.6 on 2026-05-01 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_candidat_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='push_notif_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_blocage', models.DateTimeField(auto_now_add=True)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloque_par', to='users.utilisateur')),
                ('bloqueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs_bloques', to='users.utilisateur')),
            ],
            options={
                'db_table': 'blocked_user',
                'unique_together': {('bloqueur', 'bloque')},
            },
        ),
    ]
