# Generated by Django 5.0.6 on 2026-05-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('users', '0004_utilisateur_push_notif_enabled_blockeduser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date_envoi']},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['expediteur', 'destinataire', 'date_envoi'], name='idx_msg_exp_dest_date'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['destinataire', 'est_lu'], name='idx_msg_dest_unread'),
        ),
    ]
