# Generated by Django 5.0.6 on 2026-05-16 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_message_options_message_idx_msg_exp_dest_date_and_more'),
        ('users', '0004_utilisateur_push_notif_enabled_blockeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('direct', 'Direct'), ('group', 'Group')], default='direct', max_length=10)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'conversation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'conversation_member',
            },
        ),
        migrations.CreateModel(
            name='ReadCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'read_cursor',
            },
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='idx_msg_exp_dest_date',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='idx_msg_dest_unread',
        ),
        migrations.AlterField(
            model_name='message',
            name='destinataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to='users.utilisateur'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to='users.utilisateur'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'date_envoi'], name='idx_msg_conv_date'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['expediteur', 'date_envoi'], name='idx_msg_exp_date'),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='messaging.conversation'),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_memberships', to='users.utilisateur'),
        ),
        migrations.AddField(
            model_name='readcursor',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_cursors', to='messaging.conversation'),
        ),
        migrations.AddField(
            model_name='readcursor',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.message'),
        ),
        migrations.AddField(
            model_name='readcursor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_cursors', to='users.utilisateur'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationmember',
            unique_together={('conversation', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='readcursor',
            unique_together={('conversation', 'user')},
        ),
    ]
