# Generated by Django 5.0.6 on 2026-05-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_populate_conversations_from_dms'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmember',
            name='is_invitation',
            field=models.BooleanField(default=False),
        ),
    ]
