# Generated by Django 5.0.6 on 2026-04-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('type', models.CharField(max_length=50)),
                ('date_ajout', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'media',
            },
        ),
    ]
