# Generated by Django 5.0.6 on 2026-04-26 00:15

import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_media_description_alter_media_url'),
        ('users', '0002_emailotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='date_ajout',
        ),
        migrations.RemoveField(
            model_name='media',
            name='type',
        ),
        migrations.AddField(
            model_name='media',
            name='candidat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='users.candidat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='type_media',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
