# Generated by Django 5.0.6 on 2026-04-15 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('duree_heures', models.FloatField(blank=True, null=True)),
                ('statut', models.CharField(default='en_cours', max_length=50)),
                ('candidature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='applications.candidature')),
            ],
            options={
                'db_table': 'mission',
            },
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('categorie', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('salaire', models.FloatField(blank=True, null=True)),
                ('type_contrat', models.CharField(max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('statut', models.CharField(default='ouverte', max_length=50)),
                ('recruteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='users.recruteur')),
            ],
            options={
                'db_table': 'offre',
            },
        ),
    ]
