# Generated by Django 5.0.6 on 2026-05-02 22:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_mission_date_debut_alter_mission_statut_and_more'),
        ('users', '0004_utilisateur_push_notif_enabled_blockeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('type_contrat', models.CharField(blank=True, max_length=50)),
                ('salaire_min', models.FloatField(blank=True, null=True)),
                ('localisation', models.CharField(blank=True, max_length=200)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='users.candidat')),
            ],
            options={
                'db_table': 'alerte',
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='users.candidat')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobs.offre')),
            ],
            options={
                'db_table': 'saved_job',
                'unique_together': {('candidat', 'offre')},
            },
        ),
    ]
