# Generated by Django 5.0.6 on 2026-05-19 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alerte_savedjob'),
        ('users', '0005_recentsearch_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='offre',
            name='candidate_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='offre',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offre',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offre',
            name='statut',
            field=models.CharField(choices=[('searching', 'Searching'), ('draft', 'Draft'), ('closed', 'Closed')], default='searching', max_length=50),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews_as_candidate', to='users.utilisateur')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.offre')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews_as_recruiter', to='users.utilisateur')),
            ],
            options={
                'db_table': 'interview',
            },
        ),
    ]
