# Generated by Django 5.0.6 on 2026-05-21 01:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
        ('jobs', '0004_mission_image_url_mission_location_and_more'),
        ('users', '0006_candidat_domain_candidat_titre_poste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='candidature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='applications.candidature'),
        ),
        migrations.AddField(
            model_name='mission',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offre',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offre',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='offre',
            name='logo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='offre',
            name='schedule_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='JobComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('reponse', models.TextField(blank=True)),
                ('date_question', models.DateTimeField(auto_now_add=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_comments', to='users.utilisateur')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='jobs.offre')),
            ],
            options={
                'db_table': 'job_comment',
                'ordering': ['-date_question'],
            },
        ),
        migrations.CreateModel(
            name='MissionTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0.0)),
                ('avatar_url', models.CharField(blank=True, max_length=500, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='jobs.mission')),
            ],
            options={
                'db_table': 'mission_team_member',
            },
        ),
    ]
