# Generated by Django 5.0.6 on 2026-05-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_interview_candidature_mission_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
    ]
