# Generated by Django 5.0.6 on 2026-04-15 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_postulation', models.DateField(auto_now_add=True)),
                ('message_personnalise', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(default='en_attente', max_length=50)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='users.candidat')),
            ],
            options={
                'db_table': 'candidature',
            },
        ),
    ]
