# Generated by Django 5.0.6 on 2026-05-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='date_postulation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'Pending'), ('acceptee', 'Accepted'), ('refusee', 'Rejected')], default='en_attente', max_length=50),
        ),
    ]
