# Generated by Django 5.0.6 on 2026-05-22 04:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('messaging', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='ouvert', max_length=50)),
                ('decision', models.TextField(blank=True, null=True)),
                ('target_type', models.CharField(default='user', max_length=20)),
                ('administrateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_traites', to='users.administrateur')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_emis', to='users.utilisateur')),
                ('cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_recus', to='users.utilisateur')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='messaging.message')),
            ],
            options={
                'db_table': 'signalement',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_evaluation', models.DateField(auto_now_add=True)),
                ('recruiter_reply', models.TextField(blank=True, null=True)),
                ('recruiter_name', models.CharField(blank=True, max_length=200, null=True)),
                ('recruiter_reply_date', models.DateTimeField(blank=True, null=True)),
                ('evaluateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_donnees', to='users.utilisateur')),
                ('evalue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_recues', to='users.utilisateur')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='jobs.mission')),
            ],
            options={
                'db_table': 'evaluation',
                'unique_together': {('evaluateur', 'mission')},
            },
        ),
    ]
