# Generated by Django 5.0.6 on 2026-04-15 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_evaluation', models.DateField(auto_now_add=True)),
                ('evaluateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_donnees', to='users.utilisateur')),
                ('evalue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_recues', to='users.utilisateur')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='jobs.mission')),
            ],
            options={
                'db_table': 'evaluation',
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='ouvert', max_length=50)),
                ('decision', models.TextField(blank=True, null=True)),
                ('administrateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_traites', to='users.administrateur')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_emis', to='users.utilisateur')),
                ('cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_recus', to='users.utilisateur')),
            ],
            options={
                'db_table': 'signalement',
            },
        ),
    ]
